services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/cataso/backend
      - /usr/src/cataso/backend/node_modules # node_modules はローカルと分離
      - ./.env:/usr/src/cataso/.env
    command: npm start
    working_dir: /usr/src/cataso/backend
    # tty: true # 本番環境では不要

    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=cataso
    stop_grace_period: 60s
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - 3307:3306    
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: cataso
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: